name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            web-app/client/package-lock.json
            web-app/servers/package-lock.json

      - name: Install server deps
        working-directory: web-app/servers
        run: npm ci || npm install

      - name: Install client deps
        working-directory: web-app/client
        run: npm ci || npm install

      - name: Build client
        working-directory: web-app/client
        run: npm run build --if-present

      - name: Lint (if configured)
        working-directory: web-app/client
        run: npm run lint --if-present
